# Generated by Django 5.1.1 on 2024-10-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_image_blog_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
